
# Orchestrates: preprocess -> solve (MILP if solver available, else heuristic already created) -> figures
import os, subprocess, sys
from pathlib import Path

ROOT = str(Path(__file__).resolve().parents[0])

def run(cmd):
    print(">", " ".join(cmd))
    r = subprocess.run(cmd, cwd=ROOT)
    if r.returncode != 0:
        raise SystemExit(f"Command failed: {' '.join(cmd)}")

if __name__=="__main__":
    # Preprocess
    run([sys.executable, "pipelines/preprocess.py"])
    # Try MILP
    try:
        run([sys.executable, "model/solve.py"])
    except Exception as e:
        print("MILP stage skipped:", e)
    # Figures are generated by the heuristic in this bundle already.
    print("Pipeline completed. Outputs are in outputs/tables and outputs/figures.")
